#!/bin/sh

myname="${0##*/}"

# program installed by apt
prog_sys="/usr/bin/yt-dlp"

# program installed by pipx and exported to your local bin path
prog_loc="$HOME/.local/bin/yt-dlp"

# program installed by pip in a venv
prog_vev="$VIRTUAL_ENV/bin/yt-dlp"

# the program
prog=""

if [ -x "$prog_sys" ]; then
    prog="$prog_sys"
elif [ -x "$prog_loc" ] && [ "$0" != "$(readlink "$prog_loc")" ]; then
    prog="$prog_loc"
elif [ -x "$prog_vev" ]; then
    prog="$prog_vev"
else
    printf '%s\n' "${myname}: no executable found by wrapper!"
    exit 1
fi

browser=$(xdg-settings get default-web-browser \
    | sed 's/\.desktop//; s/-browser//')

keyring=$(pgrep -a "keyring|kwallet|kdewallet" | cut -d" " -f2)

case "$keyring" in
    *gnome*)
        keyring="gnomekeyring"
        ;;
    *wallet*)
        keyring="kwallet"
        ;;
esac

if [ "$#" -gt 0 ]; then
    case "$1" in
        -h|--help)
            printf '%s\n'   "${myname}: yt-dlp wrapper"
            printf '  %s\n' "this wrapper will set the cookies-from-browser flag"
            printf '  %s\n' "as '--cookies-from-browser \${browser}+\${keyring}'"
            printf '  %s\n' "    the web browser name is determined with:"
            printf '  %s\n' "      'xdg-settings get default-web-browser'"
            printf '  %s\n' "    the keyring name is searched with:"
            printf '  %s\n' "      pgrep -a 'keyring|kwallet|kdewallet'"
            printf '  %s\n' "currently it expands to:"
            printf '  %s\n' "  --cookies-from-browser ${browser}+${keyring}"
            printf '\n'
            ;;
    esac
else
    printf '%s\n' "${myname}: no arguments passed!"
    exit 1
fi

exec $prog \
    --cookies-from-browser "${browser}"+"${keyring}" \
    "$@"
